# theme: jekyll-theme-minimal

# Name of website
# title: <center>Mariana Chaves</center>
title: Mariana Chaves
logo: photo4-modified.png
# description: Statistician and Data Scientist
show_downloads: false
google_analytics:
# markdown: kramdown
theme: jekyll-theme-minimal

