# theme: jekyll-theme-minimal
# ---
title: "EM algorithm for multivariate data"
author: "Mariana Chaves and Franz Franco Gallo"
output:
  html_document:
    code_download: yes
    highlight: tango
    number_sections: no
    theme: flatly
    toc: TRUE
    toc_float: TRUE
editor_options: 
  chunk_output_type: inline
# ---