# theme: jekyll-theme-minimal

# Name of website
title: Mariana Chaves
logo: photo2-modified.png
# description: Statistician and Data Scientist
show_downloads: false
google_analytics:
# markdown: kramdown
theme: jekyll-theme-minimal
plugins: 
 - jekyll-feed
 - jekyll-avatar



