# theme: jekyll-theme-minimal

# Name of website
title: <center>Mariana Chaves</center>
logo: photo3-modified.png
# description: Statistician and Data Scientist
show_downloads: false
google_analytics:
email: mariana.chaves-espinoza@etu.univ-cotedazur.fr
# markdown: kramdown
theme: jekyll-theme-minimal
plugins: 
 - jekyll-feed
 - jekyll-avatar
