# theme: jekyll-theme-minimal

# Name of website
# title: <center>Mariana Chaves</center>
title: Mariana Chaves
logo: img/photo4-modified.png
# description: Statistician and Data Scientist
show_downloads: false
github: false
google_analytics: true
# markdown: kramdown
theme: jekyll-theme-minimal

