# theme: jekyll-theme-minimal

# # Name of website
# title: <center>Mariana Chaves</center>
# title: Mariana Chaves
# logo: img/photo4-modified.png
# # description: Statistician and Data Scientist
# # show_downloads: false
# # github: true
# # google_analytics: true
# markdown: kramdown
# theme: jekyll-theme-minimal


title: <center>Mariana Chaves</center>
logo: img/photo4-modified.png
description: <h2>About me</h2> I'm a <strong>statistician and data scientist</strong> with 7 years of working experience in data modeling, visualization, extraction, and transformation. Recently, I have been researching natural language processing techniques and text models in the context of fallacy detection and classification. I also worked in explainable and interpretable AI. In particular, with prototype-based interpretable neural networks and local interpretable model-agnostic explanations (LIME). <link rel="stylesheet" href="/assets/css/all.min.css"> <br> <i class="fas fa-heart"></i>
show_downloads: false
# github: true
google_analytics: 
theme: jekyll-theme-minimal
